### ISSUE TITLE
Should remember last selected level of drift

### ISSUE THREAD

**Issue by igoticecream** [DarkPred/NoCreativeDrift#3]
Hello,

The mod should remember the last selected drift level.

For example, Im playing a world with the "weak" level and I close the game and come back and the level should be "weak".

**Comment by DarkPred** [comment]
Do you want to save a different drift level for each world or one across all worlds?

**Comment by igoticecream** [comment]
Hello.

I'd say it will be nice to save the last state of the drift acroll all worlds. But whatever you end up choosing it's fine.

Thanks.

**Comment by DarkPred** [comment]
Alright state now stays the same across all worlds and when closing the game

**Comment by igoticecream** [comment]
Amazing, everything is working.

Thanks a lot.
