### ISSUE TITLE
NCD does not support iron jetpacks past 4.2.1

### ISSUE THREAD

**Issue by Cynix32** [DarkPred/NoCreativeDrift#4]
**Describe the bug**
NCD does not support Iron Jetpacks 4.2.3 and prevents game from starting..

**To Reproduce**
1. Install Minecraft
2. Install Forge 36 (for minecraft 1.16)
3. Play with NCD and Iron Jetpacks 4.2.3
4. Game won't start

**Expected behavior**
Game will start

**Screenshots**

**Desktop (please complete the following information):**
MC 1.16.5
Forge 36.2.9
Windows 10
NoCreativeDrift-1.16.5-1.0.10.0.jar
IronJetpacks-1.16.5-4.2.3.jar

**Additional context**

**Comment by DarkPred** [comment]
Thanks for the notice.
Fixed in 1.0.10.1
