### ISSUE TITLE
moving extremely slow with InvMove

### ISSUE THREAD

**Issue by Aceplante** [DarkPred/NoCreativeDrift#5]
**Describe the bug**
I have both Inventory Move and your mod installed, but seem to move EXTREMELY slowly when flying with the inventory open

**To Reproduce**
Download Inventory move
Go in creative
Open inventory
press any horizontal movement key

**Expected behavior**
to move at the normal flight speed

**Desktop (please complete the following information):**
 - Mod Version Forge
 - Minecraft Version 1.18.2
 - Forge/Fabric Version latest one?

**Comment by DarkPred** [comment]
I've uploaded new versions that add support for that mod. Should anything not work correctly please open a new issue.

**Comment by Aceplante** [comment]
Sounds good ill be sure to test it out later. thank you
