### ISSUE TITLE
Update to 1.20/1.20.1

### ISSUE THREAD

**Issue by KadTheHunter** [DarkPred/NoCreativeDrift#6]
**Is your feature request related to a problem? Please describe.**
Mod won't load on 1.20/1.20.1

**Describe the solution you'd like**
An update to 1.20/1.20.1

**Describe alternatives you've considered**
Haven't found any

**Additional context**
N/A

**Comment by DarkPred** [comment]
I've uploaded beta versions for forge and fabric
